# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - '#f0c6c6'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    selectedRangeBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#f0c6c6'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"
